-- =========================================
-- QNOTA - ESQUEMA RELACIONAL (PostgreSQL 13+)
-- Sem triggers; “um principal por aluno” via índice parcial
-- =========================================

-- (Opcional) cria o banco se não existir
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_database WHERE datname='qnota') THEN
    PERFORM dblink_exec('dbname=' || current_database(), ''); -- garante extensão dblink não exigida
    EXECUTE 'CREATE DATABASE qnota';
  END IF;
END$$;

-- use este banco numa nova conexão, ou:
-- \c qnota

-- (recomendado) trabalhar em um schema dedicado
CREATE SCHEMA IF NOT EXISTS qnota;
SET search_path TO qnota;

-- COORDENADORES
CREATE TABLE IF NOT EXISTS coordenadores (
  id                 INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome               VARCHAR(255) NOT NULL,
  enderecoEletronico VARCHAR(255) NOT NULL UNIQUE,
  senhaHash          VARCHAR(255) NOT NULL,
  ativo              BOOLEAN NOT NULL DEFAULT TRUE
);

-- RESPONSAVEIS
CREATE TABLE IF NOT EXISTS responsaveis (
  id                 INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome               VARCHAR(255) NOT NULL,
  cpf                VARCHAR(14)  NOT NULL UNIQUE,
  enderecoEletronico VARCHAR(255) NOT NULL,
  status             TEXT NOT NULL DEFAULT 'ATIVO',
  CONSTRAINT ck_resp_status CHECK (status IN ('ATIVO','INADIMPLENTE','INATIVO'))
);

-- PROFESSORES
CREATE TABLE IF NOT EXISTS professores (
  id                 INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome               VARCHAR(255) NOT NULL,
  cpf                VARCHAR(14)  NOT NULL UNIQUE,
  enderecoEletronico VARCHAR(255) NOT NULL,
  especialidades     JSONB NULL
);

-- AREAS / DISCIPLINAS
CREATE TABLE IF NOT EXISTS areas_conhecimento (
  id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS disciplinas (
  id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome           VARCHAR(255) NOT NULL,
  versao         INT NOT NULL DEFAULT 1,
  idVersaoOrigem INT NULL,
  ativo          BOOLEAN NOT NULL DEFAULT TRUE,
  area_id        INT NOT NULL,
  CONSTRAINT fk_disc_area FOREIGN KEY (area_id) REFERENCES areas_conhecimento(id),
  CONSTRAINT ux_disc_nome_area_versao UNIQUE (nome, area_id, versao)
);

-- TURMAS
CREATE TABLE IF NOT EXISTS turmas (
  id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome         VARCHAR(255) NOT NULL,
  anoLetivo    INT NOT NULL,
  ativo        BOOLEAN NOT NULL DEFAULT TRUE,
  professor_id INT NOT NULL,
  CONSTRAINT fk_turma_prof FOREIGN KEY (professor_id) REFERENCES professores(id),
  CONSTRAINT ux_turma_nome_ano UNIQUE (nome, anoLetivo)
);

-- ALUNOS
CREATE TABLE IF NOT EXISTS alunos (
  id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome           VARCHAR(255) NOT NULL,
  dataNascimento DATE NOT NULL,
  ativo          BOOLEAN NOT NULL DEFAULT TRUE,
  turma_id       INT NOT NULL,
  CONSTRAINT fk_aluno_turma FOREIGN KEY (turma_id) REFERENCES turmas(id)
);

-- VÍNCULO ALUNO-RESPONSAVEL (N:N)
CREATE TABLE IF NOT EXISTS aluno_responsaveis (
  responsavel_id INT NOT NULL,
  principal      BOOLEAN NOT NULL DEFAULT FALSE,
  aluno_id       INT NOT NULL,
  PRIMARY KEY (responsavel_id, aluno_id),
  CONSTRAINT fk_ar_resp  FOREIGN KEY (responsavel_id) REFERENCES responsaveis(id) ON DELETE RESTRICT,
  CONSTRAINT fk_ar_aluno FOREIGN KEY (aluno_id)       REFERENCES alunos(id)       ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_ar_aluno ON aluno_responsaveis(aluno_id);
-- “Um principal por aluno”
CREATE UNIQUE INDEX IF NOT EXISTS ux_ar_um_principal_por_aluno
  ON aluno_responsaveis(aluno_id)
  WHERE principal = TRUE;

-- SIMULADOS
CREATE TABLE IF NOT EXISTS simulados (
  id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dataAplicacao DATE NOT NULL,
  status        TEXT NOT NULL DEFAULT 'EM_EDICAO',
  turma_id      INT NOT NULL,
  CONSTRAINT ck_sim_status CHECK (status IN ('EM_EDICAO','FINALIZADO')),
  CONSTRAINT fk_sim_turma   FOREIGN KEY (turma_id) REFERENCES turmas(id)
);
CREATE INDEX IF NOT EXISTS ix_sim_turma ON simulados(turma_id);

-- DISCIPLINAS DO SIMULADO (com pesos)
CREATE TABLE IF NOT EXISTS simulado_disciplinas (
  simulado_id   INT NOT NULL,
  disciplina_id INT NOT NULL,
  peso          DOUBLE PRECISION NOT NULL,
  PRIMARY KEY (simulado_id, disciplina_id),
  CONSTRAINT fk_sd_sim FOREIGN KEY (simulado_id)   REFERENCES simulados(id)   ON DELETE CASCADE,
  CONSTRAINT fk_sd_dis FOREIGN KEY (disciplina_id) REFERENCES disciplinas(id)
);

-- NOTAS DO ALUNO
CREATE TABLE IF NOT EXISTS notas_do_aluno (
  aluno_id       INT NOT NULL,
  simulado_id    INT NOT NULL,
  disciplina_id  INT NOT NULL,
  valor          DOUBLE PRECISION NOT NULL,
  dataLancamento TIMESTAMP NOT NULL DEFAULT NOW(),
  PRIMARY KEY (aluno_id, simulado_id, disciplina_id),
  CONSTRAINT fk_nota_aluno      FOREIGN KEY (aluno_id)      REFERENCES alunos(id)      ON DELETE CASCADE,
  CONSTRAINT fk_nota_simulado   FOREIGN KEY (simulado_id)   REFERENCES simulados(id)   ON DELETE CASCADE,
  CONSTRAINT fk_nota_disciplina FOREIGN KEY (disciplina_id) REFERENCES disciplinas(id)
);
CREATE INDEX IF NOT EXISTS ix_nota_sim  ON notas_do_aluno(simulado_id);
CREATE INDEX IF NOT EXISTS ix_nota_disc ON notas_do_aluno(disciplina_id);

-- JUSTIFICATIVAS
CREATE TABLE IF NOT EXISTS justificativas (
  id            VARCHAR(50) PRIMARY KEY,   -- gerado pela aplicação (UUID string, por exemplo)
  aluno_id      INT NOT NULL,
  simulado_id   INT NOT NULL,
  disciplina_id INT NOT NULL,
  professor_id  INT NOT NULL,
  notaAnterior  DOUBLE PRECISION NOT NULL,
  notaCorrigida DOUBLE PRECISION NOT NULL,
  texto         TEXT   NOT NULL,
  dataHora      TIMESTAMP NOT NULL DEFAULT NOW(),
  CONSTRAINT fk_just_aluno      FOREIGN KEY (aluno_id)      REFERENCES alunos(id)      ON DELETE CASCADE,
  CONSTRAINT fk_just_simulado   FOREIGN KEY (simulado_id)   REFERENCES simulados(id)   ON DELETE CASCADE,
  CONSTRAINT fk_just_disciplina FOREIGN KEY (disciplina_id) REFERENCES disciplinas(id),
  CONSTRAINT fk_just_prof       FOREIGN KEY (professor_id)  REFERENCES professores(id)
);
CREATE INDEX IF NOT EXISTS ix_just_nota ON justificativas(aluno_id, simulado_id, disciplina_id);

-- RANKINGS
CREATE TABLE IF NOT EXISTS rankings (
  id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  congelado   BOOLEAN NOT NULL DEFAULT FALSE,
  simulado_id INT NOT NULL UNIQUE,
  CONSTRAINT fk_rank_sim FOREIGN KEY (simulado_id) REFERENCES simulados(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ranking_linhas (
  ranking_id INT NOT NULL,
  aluno_id   INT NOT NULL,
  media      DOUBLE PRECISION NOT NULL,
  posicao    INT NOT NULL,
  PRIMARY KEY (ranking_id, aluno_id),
  CONSTRAINT fk_rl_rank  FOREIGN KEY (ranking_id) REFERENCES rankings(id) ON DELETE CASCADE,
  CONSTRAINT fk_rl_aluno FOREIGN KEY (aluno_id)   REFERENCES alunos(id),
  CONSTRAINT ux_rl_rank_pos UNIQUE (ranking_id, posicao)
);
