services:
  postgres:
    container_name: qnota-postgres
    image: postgres:18
    environment:
      POSTGRES_DB: qnota
      POSTGRES_USER: qnota
      POSTGRES_PASSWORD: qnota
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U qnota"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres:

