-- =========================================
-- QNOTA - ESQUEMA RELACIONAL (H2 Database)
-- Adaptado do script PostgreSQL original
-- =========================================

-- COORDENADORES
CREATE TABLE IF NOT EXISTS coordenadores (
  id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome                VARCHAR(255) NOT NULL,
  endereco_eletronico VARCHAR(255) NOT NULL UNIQUE,
  senha_hash          VARCHAR(255) NOT NULL,
  ativo               BOOLEAN NOT NULL DEFAULT TRUE
);

-- RESPONSAVEIS
CREATE TABLE IF NOT EXISTS responsaveis (
  id                 INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome               VARCHAR(255) NOT NULL,
  cpf                VARCHAR(14)  NOT NULL UNIQUE,
  endereco_eletronico VARCHAR(255) NOT NULL,
  status             VARCHAR(20) NOT NULL DEFAULT 'ATIVO',
  CONSTRAINT ck_resp_status CHECK (status IN ('ATIVO','INADIMPLENTE','INATIVO'))
);

-- PROFESSORES
CREATE TABLE IF NOT EXISTS professores (
  id                  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome                VARCHAR(255) NOT NULL,
  cpf                 VARCHAR(14)  NOT NULL UNIQUE,
  endereco_eletronico VARCHAR(255) NOT NULL,
  especialidades      VARCHAR(1000) NULL  -- JSON armazenado como string no H2
);

-- AREAS / DISCIPLINAS
CREATE TABLE IF NOT EXISTS areas_conhecimento (
  id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS disciplinas (
  id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome           VARCHAR(255) NOT NULL,
  versao         INT NOT NULL DEFAULT 1,
  id_versao_origem INT NULL,
  ativo          BOOLEAN NOT NULL DEFAULT TRUE,
  area_id        INT NOT NULL,
  CONSTRAINT fk_disc_area FOREIGN KEY (area_id) REFERENCES areas_conhecimento(id),
  CONSTRAINT ux_disc_nome_area_versao UNIQUE (nome, area_id, versao)
);

-- TURMAS
CREATE TABLE IF NOT EXISTS turmas (
  id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome         VARCHAR(255) NOT NULL,
  ano_letivo   INT NOT NULL,
  ativo        BOOLEAN NOT NULL DEFAULT TRUE,
  professor_id INT NOT NULL,
  CONSTRAINT fk_turma_prof FOREIGN KEY (professor_id) REFERENCES professores(id),
  CONSTRAINT ux_turma_nome_ano UNIQUE (nome, ano_letivo)
);

-- ALUNOS
CREATE TABLE IF NOT EXISTS alunos (
  id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome           VARCHAR(255) NOT NULL,
  data_nascimento DATE NOT NULL,
  ativo          BOOLEAN NOT NULL DEFAULT TRUE,
  turma_id       INT NOT NULL,
  CONSTRAINT fk_aluno_turma FOREIGN KEY (turma_id) REFERENCES turmas(id)
);

-- VÍNCULO ALUNO-RESPONSAVEL (N:N)
CREATE TABLE IF NOT EXISTS aluno_responsaveis (
  responsavel_id INT NOT NULL,
  principal      BOOLEAN NOT NULL DEFAULT FALSE,
  aluno_id       INT NOT NULL,
  PRIMARY KEY (responsavel_id, aluno_id),
  CONSTRAINT fk_ar_resp  FOREIGN KEY (responsavel_id) REFERENCES responsaveis(id),
  CONSTRAINT fk_ar_aluno FOREIGN KEY (aluno_id)       REFERENCES alunos(id)       ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_ar_aluno ON aluno_responsaveis(aluno_id);
-- "Um principal por aluno" - validação deve ser feita na aplicação
-- Nota: H2 não suporta índices parciais com WHERE de forma confiável
-- A regra de negócio "um principal por aluno" deve ser garantida na camada de domínio

-- SIMULADOS
CREATE TABLE IF NOT EXISTS simulados (
  id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  data_aplicacao DATE NOT NULL,
  status         VARCHAR(20) NOT NULL DEFAULT 'EM_EDICAO',
  turma_id       INT NOT NULL,
  CONSTRAINT ck_sim_status CHECK (status IN ('EM_EDICAO','FINALIZADO')),
  CONSTRAINT fk_sim_turma   FOREIGN KEY (turma_id) REFERENCES turmas(id)
);
CREATE INDEX IF NOT EXISTS ix_sim_turma ON simulados(turma_id);

-- DISCIPLINAS DO SIMULADO (com pesos)
CREATE TABLE IF NOT EXISTS simulado_disciplinas (
  simulado_id   INT NOT NULL,
  disciplina_id INT NOT NULL,
  peso          DOUBLE NOT NULL,
  PRIMARY KEY (simulado_id, disciplina_id),
  CONSTRAINT fk_sd_sim FOREIGN KEY (simulado_id)   REFERENCES simulados(id)   ON DELETE CASCADE,
  CONSTRAINT fk_sd_dis FOREIGN KEY (disciplina_id) REFERENCES disciplinas(id)
);

-- NOTAS DO ALUNO
CREATE TABLE IF NOT EXISTS notas_do_aluno (
  aluno_id       INT NOT NULL,
  simulado_id    INT NOT NULL,
  disciplina_id  INT NOT NULL,
  valor          DOUBLE NOT NULL,
  data_lancamento TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (aluno_id, simulado_id, disciplina_id),
  CONSTRAINT fk_nota_aluno      FOREIGN KEY (aluno_id)      REFERENCES alunos(id)      ON DELETE CASCADE,
  CONSTRAINT fk_nota_simulado   FOREIGN KEY (simulado_id)   REFERENCES simulados(id)   ON DELETE CASCADE,
  CONSTRAINT fk_nota_disciplina FOREIGN KEY (disciplina_id) REFERENCES disciplinas(id)
);
CREATE INDEX IF NOT EXISTS ix_nota_sim  ON notas_do_aluno(simulado_id);
CREATE INDEX IF NOT EXISTS ix_nota_disc ON notas_do_aluno(disciplina_id);

-- JUSTIFICATIVAS
CREATE TABLE IF NOT EXISTS justificativas (
  id            VARCHAR(50) PRIMARY KEY,
  aluno_id      INT NOT NULL,
  simulado_id   INT NOT NULL,
  disciplina_id INT NOT NULL,
  professor_id  INT NOT NULL,
  nota_anterior  DOUBLE NOT NULL,
  nota_corrigida DOUBLE NOT NULL,
  texto          VARCHAR(10000) NOT NULL,
  data_hora      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_just_aluno      FOREIGN KEY (aluno_id)      REFERENCES alunos(id)      ON DELETE CASCADE,
  CONSTRAINT fk_just_simulado   FOREIGN KEY (simulado_id)   REFERENCES simulados(id)   ON DELETE CASCADE,
  CONSTRAINT fk_just_disciplina FOREIGN KEY (disciplina_id) REFERENCES disciplinas(id),
  CONSTRAINT fk_just_prof       FOREIGN KEY (professor_id)  REFERENCES professores(id)
);
CREATE INDEX IF NOT EXISTS ix_just_nota ON justificativas(aluno_id, simulado_id, disciplina_id);

-- RANKINGS
CREATE TABLE IF NOT EXISTS rankings (
  id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  congelado   BOOLEAN NOT NULL DEFAULT FALSE,
  simulado_id INT NOT NULL UNIQUE,
  CONSTRAINT fk_rank_sim FOREIGN KEY (simulado_id) REFERENCES simulados(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ranking_linhas (
  ranking_id INT NOT NULL,
  aluno_id   INT NOT NULL,
  media      DOUBLE NOT NULL,
  posicao    INT NOT NULL,
  PRIMARY KEY (ranking_id, aluno_id),
  CONSTRAINT fk_rl_rank  FOREIGN KEY (ranking_id) REFERENCES rankings(id) ON DELETE CASCADE,
  CONSTRAINT fk_rl_aluno FOREIGN KEY (aluno_id)   REFERENCES alunos(id),
  CONSTRAINT ux_rl_rank_pos UNIQUE (ranking_id, posicao)
);

